# Generated by Django 5.0.2 on 2024-02-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='working',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
